### ISSUE TITLE
你好，我用的是1.3.1版的Android Studio，加载项目后有错误

### ISSUE THREAD

**Issue by himon** [Jude95/Beam#3]
Error:Unable to find method 'org.gradle.api.internal.project.ProjectInternal.getConfigurations()Lorg/gradle/api/internal/artifacts/configurations/ConfigurationContainerInternal;'.

Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by Jude95** [comment]
这些你本地Gradle配置相关,与本项目无关（~~我也不知道~~）。而且...Android Studio都2.0bate2了。并且这个项目没可运行demo所以也没什么编译的必要。
