### ISSUE TITLE
BeamBaseActivity 代码疑问

### ISSUE THREAD

**Issue by amosbake** [Jude95/Beam#4]
在`BeamBaseActivity`中有获取根视图的方法
`mContentParent= (FrameLayout) findViewById(android.R.id.content);`
但`android.R.id.content`对应的组件应该是`LinearLayout`吧，而且在后续的代码中也未用到`FrameLayout`的特性.能否用`ViewGroup`或`LinearLayout`代替呢

**Comment by Jude95** [comment]
是FrameLayout哟，如果是LinearLayout强转成FrameLayout是会崩溃的。
然后用ViewGroup来引用也不会提升性能，反而会隔离掉FrameLayout的API。
