### ISSUE TITLE
我已经在功能清单文件注册了。提示没有注册

### ISSUE THREAD

**Issue by yangchaojiang** [Jude95/Beam#5]
看能一下什么错误吗？ 谢谢

![qq 20160302170429](https://cloud.githubusercontent.com/assets/13806413/13455529/e7da70f8-e098-11e5-8d47-27fb51b5542d.png)

**Comment by Jude95** [comment]
要自定义application在里面Beam.init();

**Comment by yangchaojiang** [comment]
问题解决了。谢谢了
现在有一个新问题。model 在功能清单文件注册model。 请问只能注册一个吗？我有多个model 怎么办。
 <meta-data
            android:name="MODEL"
            android:value="beam.com.tests.DataModel" />
        <activity>
 <meta-data
            android:name="MODEL"
            android:value="beam.com.tests.UserModel" />
        <activity>
第二个就报错了。第二个的名称怎么改的。谢谢了

**Comment by Jude95** [comment]
android:name="MODEL"
android:value="beam.com.tests.UserModel,
beam.com.tests.DataModel
" />

**Comment by yangchaojiang** [comment]
知道了。谢谢。
那我加你qq好友！ 有问题随时问你。， 可以吗？
