### ISSUE TITLE
找不到data(5.5)

### ISSUE THREAD

**Issue by sfyc23** [Jude95/Beam#7]
![image](https://cloud.githubusercontent.com/assets/7067207/14137916/d0bd7a04-f69c-11e5-9ab5-d6b8ca947686.png)
![image](https://cloud.githubusercontent.com/assets/7067207/14137925/e27bd678-f69c-11e5-8cd0-e2ba12a4ab55.png)

**Comment by Jude95** [comment]
data方法是什么..你想实现什么样的需求？
