### ISSUE TITLE
屏幕旋转(view意外退出)调用presenter方法有时空指针

### ISSUE THREAD

**Issue by morenever** [Jude95/Beam#8]
getView().banner_text.setPages(
                new CBViewHolderCreator<TextHolderView>() {
                    @Override
                    public TextHolderView createHolder() {
                        return new TextHolderView();
                    }
                },  getView().notice_list);

类似这种结构的会出错。如果将该方法放在view中则不会出错
错误log:Attempt to invoke virtual method 'com.bigkoo.convenientbanner.ConvenientBanner com.bigkoo.convenientbanner.ConvenientBanner.setPages(com.bigkoo.convenientbanner.holder.CBViewHolderCreator, java.util.List)' on a null object reference

**Comment by Jude95** [comment]
呃，这个错说的是ConvenientBanner的setPages空指针不是.banner_text空指针吧？
应该是你的业务逻辑问题吧？
getView是不会返回空的。

**Comment by morenever** [comment]
找到原因了,好像错误和butterKnife有关。我做了缓存，当activity横屏(或者意外退出)重建时，我直接把缓存数据传给onSucess（）方法，这个时候Butterknife @Bind R.id.banner_text  好像没执行。所以banner_text空指针。手动换成findViewByid就不会出错了。
